### PR TITLE
Sets The Alien Whitelists

### PR DESCRIPTION
**Pull request by ghost**
Sets the various races and languages to restricted / whitelisted where
needed.

### CODE REVIEW

**Comment by ghost** [comment]
Make sure to enable the alien whitelist in the CFG after pulling this or bad things will happen.

**Review by JakeDaBoss — CHANGES_REQUESTED** [review]
Changelog please.

**Review by JakeDaBoss — CHANGES_REQUESTED** [review]
Aviskree does not need to be whitelisted

**Comment by ghost** [comment]
They're not, stop being silly and notice the page break between that previous whitelisted race and where I corrected Aviskree having 2 languages + their race language. The only race actually whitelisted is the diona which is the only one you said not to allow people to join as but not to remove either.

**Review by JakeDaBoss — APPROVED** [review]

**Pull request merged**
