### PR TITLE
Collective PR

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Needs a changelog but should be good code wise.

**Review by JakeDaBoss — COMMENTED** [review]
I'll review this shortly.

**Review by JakeDaBoss — DISMISSED** [review]
Mentors should be able to paralyze as well. It's very well possible the mapping changes need to be omitted, as I'm remodeling the medbay a large portion of today and tomorrow.

**Comment by ghost** [comment]
Removed the Edits to the Station Zlevels and mentors should be included in the list now

**Review by JakeDaBoss — APPROVED** [review]
Good.

**Pull request merged**
